services:
  rails_app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      RAILS_ENV: development
      OTEL_EXPORTER_OTLP_ENDPOINT: http://jaeger:4318
    command:
      - "bin/dev"
    volumes:
      - .:/rails
      - rails_app_node_modules:/rails/node_modules
    ports:
      - 80:80
    tty: true

  jaeger:
    image: jaegertracing/all-in-one:latest
    environment:
      COLLECTOR_ZIPKIN_HOST_PORT: ":9411"
      COLLECTOR_OTLP_ENABLED: "true"
    ports:
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
      - "14250:14250"
      - "14268:14268"
      - "14269:14269"
      - "9411:9411"

volumes:
  rails_app_node_modules:
