services:
  rails_app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      RAILS_ENV: development
    command:
      - "bin/dev"
    volumes:
      - .:/rails
      - rails_app_node_modules:/rails/node_modules
    ports:
      - 3000:3000

volumes:
  rails_app_node_modules:
