services:
  rails_app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      RAILS_ENV: development
    command:
      - "./bin/rails"
      - "server"
      - "-b"
      - "0.0.0.0"
    volumes:
      - .:/rails
    ports:
      - 3000:3000
