services:
  rails_app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      RAILS_ENV: development
    command:
      - "bin/dev"
    volumes:
      - .:/rails
    ports:
      - 3000:3000
